### ISSUE TITLE
Not able to use in react please help

### ISSUE THREAD

**Issue by Nagu07** [sharethis-github/sharethis-reactjs#20]
Module build failed please find the error below. Please help

ERROR in ./node_modules/sharethis-reactjs/dist/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "@babel/preset-env" relative to directory "C:\\Users\\Nagu\\Documents\\Projects\\React_study\\original\\ExpensifyApp\\node_modules\\sharethis-reactjs"
    at C:\Users\Nagu\Documents\Projects\React_study\original\ExpensifyApp\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\Users\Nagu\Documents\Projects\React_study\original\ExpensifyApp\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\Users\Nagu\Documents\Projects\React_study\original\ExpensifyApp\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\Users\Nagu\Documents\Projects\React_study\original\ExpensifyApp\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\Users\Nagu\Documents\Projects\React_study\original\ExpensifyApp\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Users\Nagu\Documents\Projects\React_study\original\ExpensifyApp\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Users\Nagu\Documents\Projects\React_study\original\ExpensifyApp\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Users\Nagu\Documents\Projects\React_study\original\ExpensifyApp\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\Nagu\Documents\Projects\React_study\original\ExpensifyApp\node_modules\babel-loader\lib\index.js:50:20)
 @ ./src/components/ViewExpenseItem.js 19:24-52
 @ ./src/components/ViewExpense.js
 @ ./src/routers/AppRouter.js
 @ ./src/app.js

**Comment by lucasflomuller** [comment]
Did you found a fix for it? If you didn't please send more information, specifically about your bundle configuration and package.json, I think maybe there's a problem regarding the versions of your babel.
